# -*- coding: utf-8 -*-
"""preprocesscomments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGxS_mvqPfzTF1eGLWESw5seF0xFSPsV
"""

!pip install pandas langdetect openpyxl emoji

import pandas as pd
import re
import emoji
from langdetect import detect
from langdetect.lang_detect_exception import LangDetectException

# Load Excel file
df = pd.read_excel("/content/merged_output.xlsx")

# Keep only Comment column
df = df[["Comment"]]

# Remove empty rows
df.dropna(inplace=True)

# Remove duplicate comments
df.drop_duplicates(inplace=True)

# Function to clean text
def clean_comment(text):

    text = str(text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Remove symbols emojis
    text = re.sub(
        r"[^\w\s]",
        "",
        text
    )

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

# Apply cleaning
df["Comment"] = df["Comment"].apply(clean_comment)

# Function to keep ONLY English comments
def is_english(text):

    # Remove emojis before language detection
    text_no_emoji = emoji.replace_emoji(text, replace='')

    # Remove empty texts after emoji removal
    if text_no_emoji.strip() == "":
        return False

    try:
        return detect(text_no_emoji) == "en"
    except LangDetectException:
        return False

# Keep only English comments
df = df[df["Comment"].apply(is_english)]

# Keep only comments with more than 4 words
df = df[df["Comment"].apply(lambda x: len(x.split()) > 4)]

# Reset index
df.reset_index(drop=True, inplace=True)

# Save cleaned dataset
df.to_excel("cleaned_youtube_comments.xlsx", index=False)

print("Preprocessing completed successfully!")
print(df.head())

from google.colab import files

files.download("cleaned_youtube_comments.xlsx")

