# -*- coding: utf-8 -*-
"""youtube_comments.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCCOJRsqAYyZVjIw77u8ulZQAFjPPoyu
"""

!pip install google-api-python-client pandas openpyxl

from googleapiclient.discovery import build
import pandas as pd

# Your YouTube API Key
API_KEY = "AIzaSyBn5qo-iIQUxu5yYxGhk1Bm7IQcif0XnSc"

# YouTube Video ID
VIDEO_URL = "https://youtu.be/o7W7OvETO40?si=NSqXwsvSkGKza5MG"
# Extract the actual video ID from the URL
VIDEO_ID = VIDEO_URL.split('/')[-1].split('?')[0]

# Connect to YouTube API
youtube = build(
    "youtube",
    "v3",
    developerKey=API_KEY
)

comments = []

# Request comments
request = youtube.commentThreads().list(
    part="snippet",
    videoId=VIDEO_ID,
    maxResults=100
)

response = request.execute()

# Loop through all comments
while request:

    for item in response["items"]:

        comment = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]

        author = item["snippet"]["topLevelComment"]["snippet"]["authorDisplayName"]

        published = item["snippet"]["topLevelComment"]["snippet"]["publishedAt"]

        like_count = item["snippet"]["topLevelComment"]["snippet"]["likeCount"]

        comments.append({
            "Author": author,
            "Comment": comment,
            "Likes": like_count,
            "Published": published
        })

    request = youtube.commentThreads().list_next(
        request,
        response
    )

    if request:
        response = request.execute()

# Convert to DataFrame
df = pd.DataFrame(comments)

# Save as CSV
df.to_csv("youtube_comments.csv", index=False)

# Save as Excel
df.to_excel("youtube_comments.xlsx", index=False)

print("Comments saved successfully!")
print("Total Comments:", len(df))

from google.colab import files
files.download("youtube_comments.xlsx")

