# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCzY5UqLe5_Y97GDItHppMkv9bzoT2xV
"""

from flask import Flask, render_template, request
import joblib

# Load model
model = joblib.load("model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():

    comment = request.form["comment"]

    # Convert text to vector
    comment_vector = vectorizer.transform([comment])

    # Predict emotion
    prediction = model.predict(comment_vector)[0]

    return render_template(
        "index.html",
        prediction=prediction,
        comment=comment
    )

if __name__ == "__main__":
    app.run(debug=True)

